name: Release Drafter

on:
  push:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:

jobs:
  update_release_draft:
    name: Update Release Draft
    uses: s4u/.github/.github/workflows/release-drafter.yml@master
